-- MySQL Script generated by MySQL Workbench
-- Thu Jan 23 23:59:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ICA_Permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ICA_Permission` ;

CREATE TABLE IF NOT EXISTS `ICA_Permission` (
                                                `PER_ID` INT NOT NULL AUTO_INCREMENT,
                                                `PER_Libelle` VARCHAR(128) NOT NULL,
                                                PRIMARY KEY (`PER_ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICA_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ICA_User` ;

CREATE TABLE IF NOT EXISTS `ICA_User` (
                                          `USE_UUID` VARCHAR(128) NOT NULL,
                                          `USE_NOM` VARCHAR(128) NOT NULL,
                                          `USE_EMAIL` VARCHAR(128) NOT NULL,
                                          PRIMARY KEY (`USE_UUID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICA_Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ICA_Role` ;

CREATE TABLE IF NOT EXISTS `ICA_Role` (
                                          `ROL_ID` INT NOT NULL AUTO_INCREMENT,
                                          `ROL_Libelle` VARCHAR(64) NOT NULL,
                                          PRIMARY KEY (`ROL_ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICA_Role_has_Permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ICA_Role_has_Permission` ;

CREATE TABLE IF NOT EXISTS `ICA_Role_has_Permission` (
                                                         `PER_ID` INT NOT NULL,
                                                         `ROL_ID` INT NOT NULL,
                                                         PRIMARY KEY (`PER_ID`, `ROL_ID`),
                                                         INDEX `fk_ICA_Permission_has_ICA_Role_ICA_Role1_idx` (`ROL_ID` ASC) VISIBLE,
                                                         INDEX `fk_ICA_Permission_has_ICA_Role_ICA_Permission_idx` (`PER_ID` ASC) VISIBLE,
                                                         CONSTRAINT `fk_ICA_Permission_has_ICA_Role_ICA_Permission`
                                                             FOREIGN KEY (`PER_ID`)
                                                                 REFERENCES `ICA_Permission` (`PER_ID`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION,
                                                         CONSTRAINT `fk_ICA_Permission_has_ICA_Role_ICA_Role1`
                                                             FOREIGN KEY (`ROL_ID`)
                                                                 REFERENCES `ICA_Role` (`ROL_ID`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICA_User_has_Permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ICA_User_has_Permission` ;

CREATE TABLE IF NOT EXISTS `ICA_User_has_Permission` (
                                                         `USE_UUID` VARCHAR(128) NOT NULL,
                                                         `PER_ID` INT NOT NULL,
                                                         PRIMARY KEY (`USE_UUID`, `PER_ID`),
                                                         INDEX `fk_ICA_User_has_ICA_Permission_ICA_Permission1_idx` (`PER_ID` ASC) VISIBLE,
                                                         INDEX `fk_ICA_User_has_ICA_Permission_ICA_User1_idx` (`USE_UUID` ASC) VISIBLE,
                                                         CONSTRAINT `fk_ICA_User_has_ICA_Permission_ICA_User1`
                                                             FOREIGN KEY (`USE_UUID`)
                                                                 REFERENCES `ICA_User` (`USE_UUID`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION,
                                                         CONSTRAINT `fk_ICA_User_has_ICA_Permission_ICA_Permission1`
                                                             FOREIGN KEY (`PER_ID`)
                                                                 REFERENCES `ICA_Permission` (`PER_ID`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICA_User_has_Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ICA_User_has_Role` ;

CREATE TABLE IF NOT EXISTS `ICA_User_has_Role` (
                                                   `USE_UUID` VARCHAR(128) NOT NULL,
                                                   `ROL_ID` INT NOT NULL,
                                                   PRIMARY KEY (`USE_UUID`, `ROL_ID`),
                                                   INDEX `fk_ICA_User_has_ICA_Role_ICA_Role1_idx` (`ROL_ID` ASC) VISIBLE,
                                                   INDEX `fk_ICA_User_has_ICA_Role_ICA_User1_idx` (`USE_UUID` ASC) VISIBLE,
                                                   CONSTRAINT `fk_ICA_User_has_ICA_Role_ICA_User1`
                                                       FOREIGN KEY (`USE_UUID`)
                                                           REFERENCES `ICA_User` (`USE_UUID`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_ICA_User_has_ICA_Role_ICA_Role1`
                                                       FOREIGN KEY (`ROL_ID`)
                                                           REFERENCES `ICA_Role` (`ROL_ID`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICA_EDT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ICA_EDT` ;

CREATE TABLE IF NOT EXISTS `ICA_EDT` (
                                         `EDT_ID` INT NOT NULL AUTO_INCREMENT,
                                         `EDT_Link` VARCHAR(1024) NOT NULL,
                                         `EDT_Name` VARCHAR(64) NOT NULL,
                                         PRIMARY KEY (`EDT_ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICA_Appartient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ICA_Appartient` ;

CREATE TABLE IF NOT EXISTS `ICA_Appartient` (
                                                `EDT_ID` INT NOT NULL,
                                                `USE_UUID` VARCHAR(128) NOT NULL,
                                                PRIMARY KEY (`EDT_ID`, `USE_UUID`),
                                                INDEX `fk_ICA_EDT_has_ICA_Prof_ICA_EDT1_idx` (`EDT_ID` ASC) VISIBLE,
                                                INDEX `fk_ICA_APPARTIENT_ICA_User1_idx` (`USE_UUID` ASC) VISIBLE,
                                                CONSTRAINT `fk_ICA_EDT_has_ICA_Prof_ICA_EDT1`
                                                    FOREIGN KEY (`EDT_ID`)
                                                        REFERENCES `ICA_EDT` (`EDT_ID`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
                                                CONSTRAINT `fk_ICA_APPARTIENT_ICA_User1`
                                                    FOREIGN KEY (`USE_UUID`)
                                                        REFERENCES `ICA_User` (`USE_UUID`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ICA_Calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ICA_Calendar` ;

CREATE TABLE IF NOT EXISTS `ICA_Calendar` (
                                              `USE_UUID` VARCHAR(128) NOT NULL,
                                              `CAL_HORAIRE_DEPART` DATETIME NOT NULL,
                                              `CAL_HORAIRE_FIN` DATETIME NOT NULL,
                                              `CAL_Libelle` VARCHAR(128) NOT NULL,
                                              `CAL_ID` INT NOT NULL AUTO_INCREMENT,
                                              PRIMARY KEY (`CAL_ID`),
                                              CONSTRAINT `fk_ICA_Calendar_ICA_User1`
                                                  FOREIGN KEY (`USE_UUID`)
                                                      REFERENCES `ICA_User` (`USE_UUID`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
