INSERT INTO ICA_Permission VALUES(1, "*");
INSERT INTO ICA_Role VALUES(1, "Super Admin");
INSERT INTO ICA_ROLE_HAS_PERMISSION VALUES(1, 1);


INSERT INTO ICA_User VALUES(22401769);
INSERT INTO ICA_USER_HAS_ROLE VALUES(22401769, 1);

