SELECT * FROM (SELECT PER_ID, PER_Libelle, true as 'Boolean' FROM ICA_Permission JOIN ICA_ROLE_HAS_PERMISSION USING (PER_ID) JOIN ICA_Role USING (ROL_ID) WHERE ROL_ID = ? UNION SELECT PER_ID, PER_Libelle, false as 'Boolean' FROM ICA_Permission WHERE PER_ID NOT IN ( SELECT PER_ID FROM ICA_Permission JOIN ICA_ROLE_HAS_PERMISSION USING (PER_ID) JOIN ICA_Role USING (ROL_ID) WHERE ROL_ID = ? )) as T1 ORDER BY PER_ID

SELECT * FROM ICA_Role JOIN ICA_USER_HAS_ROLE USING (ROL_ID) WHERE USE_UUID = ?;



SELECT * FROM (
SELECT ROL_ID, ROL_Libelle, true as 'Boolean'
FROM ICA_Role
JOIN ICA_USER_HAS_ROLE USING (ROL_ID)
WHERE USE_UUID = ?
UNION
SELECT ROL_ID, ROL_Libelle, false as 'Boolean'
FROM ICA_Role
WHERE ROL_ID NOT IN (
    SELECT ROL_ID
    FROM ICA_Role
    JOIN ICA_USER_HAS_ROLE USING (ROL_ID)
    WHERE USE_UUID = ?
)) as T1 ORDER BY ROL_ID;

select * from ICA_User