CREATE OR REPLACE VIEW ICA_User_Permission AS
SELECT * FROM (
    SELECT USE_UUID, PER_ID, PER_Libelle FROM ICA_User JOIN ICA_USER_HAS_PERMISSION USING (USE_UUID) JOIN ICA_Permission USING (PER_ID)
                            UNION
    SELECT USE_UUID, PER_ID, PER_Libelle FROM ICA_User JOIN ICA_USER_HAS_ROLE USING (USE_UUID) LEFT JOIN ICA_ROLE_HAS_PERMISSION USING (ROL_ID) JOIN ICA_Permission USING (PER_ID)

) AS T1
